# Generated by Django 3.2.8 on 2022-03-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_friendrequest1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
